In [36]:
import numpy as np
import pandas as pd
%precision 3

'%.3f'

In [37]:
df = pd.read_csv('../data/ch2_scores_em.csv',index_col='student number')
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [38]:
scores=np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58])

In [39]:
scores_df = pd.DataFrame({'score':scores}, index=pd.Index(['A','B', 'C', 'D', 'E',
                                                           'F','G','H','I','J']
                                                          ,name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [40]:
sum(scores) / len(scores)

55.000

In [41]:
np.mean(scores)

55.000

In [42]:
scores_df.mean()

score    55.0
dtype: float64

In [43]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69])

In [44]:
n = len(sorted_scores)
if n%2==0:
    m0=sorted_scores[n//2-1]
    m1=sorted_scores[n//2]
    median=(m0+m1)/2
else:
    median=sorted_scores[(n+1)//2-1]
median

56.500

In [45]:
np.median(scores)

56.500

In [46]:
scores_df.median()

score    56.5
dtype: float64

In [47]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [48]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [49]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [50]:
another_scores = [50, 60, 58, 54, 51, 56, 57, 53, 52, 59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [51]:
np.mean(another_deviation)

0.000

In [52]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [53]:
summary_df.mean()

score        55.0
deviation     0.0
dtype: float64

In [54]:
np.mean(deviation**2)

86.000

In [55]:
np.var(scores)

86.000

In [56]:
scores_df.var()

score    95.555556
dtype: float64

In [57]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [59]:
np.sqrt(np.var(scores, ddof=0))

9.274

In [60]:
np.std(scores, ddof=0)

9.274

In [61]:
np.max(scores) - np.min(scores)

np.int64(28)

In [62]:
scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.000

In [63]:
pd.Series(scores).describe()

count    10.000000
mean     55.000000
std       9.775252
min      41.000000
25%      48.250000
50%      56.500000
75%      63.250000
max      69.000000
dtype: float64

In [64]:
z=(scores - np.mean(scores))/np.std(scores)
z

array([-1.402,  1.51 ,  0.108, -1.51 ,  0.216, -0.755,  1.078, -0.647,
        1.078,  0.323])

In [65]:
np.mean(z), np.std(z, ddof=0)

(-0.000, 1.000)

In [67]:
z = 50 + 10 * (scores - np.mean(scores))/np.std(scores)
z

array([35.982, 65.097, 51.078, 34.903, 52.157, 42.452, 60.783, 43.53 ,
       60.783, 53.235])

In [68]:
scores_df['deviation value'] = z
scores_df

score  deviation value
student                        
A           42        35.981739
B           69        65.096588
C           56        51.078328
D           41        34.903412
E           57        52.156655
F           48        42.451706
G           65        60.783277
H           49        43.530034
I           65        60.783277
J           58        53.234983

In [69]:
#50명의 영어 점수 array
english_scores = np.array(df['english'])
#Series로 변환하여 describe를 표시
pd.Series(english_scores).describe()

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [70]:
freq, _ = np.histogram(english_scores, bins=10, range=(0, 100))
freq

array([ 0,  0,  0,  2,  8, 16, 18,  6,  0,  0])

In [71]:
# 0~10, 10~20, ... 이라는 문자열의 리스트를 작성
freq_class = [f'{i}~{i+10}' for i in range(0, 100, 10)]
#freq_class를 인덱스로 DataFrame를 작성
freq_dist_df = pd.DataFrame({'frequency':freq}, index=pd.Index(freq_class, name='class'))
freq_dist_df

frequency
class            
0~10            0
10~20           0
20~30           0
30~40           2
40~50           8
50~60          16
60~70          18
70~80           6
80~90           0
90~100          0

In [72]:
for a in range(7):
    print(a)

0
1
2
3
4
5
6


In [73]:
for a in range(10, 5, -1):
    print(a)

10
9
8
7
6


In [74]:
for a in range(20, 31, 2):
    print(a)

20
22
24
26
28
30


In [76]:
total = 0
for i in range(1, 10):
    total = total + i
print(total)

45


In [77]:
total = 0
for i in range(1, 10, 2):
    total = total + i
print(total)

25


In [78]:
class_value = [(i+(i+10))//2 for i in range(0, 100, 10)]
class_value

[5, 15, 25, 35, 45, 55, 65, 75, 85, 95]

In [79]:
rel_freq = freq/freq.sum()
rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.16, 0.32, 0.36, 0.12, 0.  , 0.  ])

In [80]:
cum_rel_freq = np.cumsum(rel_freq)
cum_rel_freq

array([0.  , 0.  , 0.  , 0.04, 0.2 , 0.52, 0.88, 1.  , 1.  , 1.  ])

In [85]:
freq_dist_df['class value'] = class_value
freq_dist_df['relative frequency'] = rel_freq
freq_dist_df['cumulative relative frequency'] = cum_rel_freq
freq_dist_df = freq_dist_df[['class value', 'frequency', 'relative frequency','cumulative relative frequency']]
freq_dist_df

class value  frequency  relative frequency  \
class                                                
0~10              5          0                0.00   
10~20            15          0                0.00   
20~30            25          0                0.00   
30~40            35          2                0.04   
40~50            45          8                0.16   
50~60            55         16                0.32   
60~70            65         18                0.36   
70~80            75          6                0.12   
80~90            85          0                0.00   
90~100           95          0                0.00   

        cumulative relative frequency  
class                                  
0~10                             0.00  
10~20                            0.00  
20~30                            0.00  
30~40                            0.04  
40~50                            0.20  
50~60                            0.52  
60~70                            0.88  
70~80                            1.00  
80~90                            1.00  
90~100                           1.00